CREATE TABLE IF NOT EXISTS `Topic` (
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Post` (
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  id_topic int(11) NOT NULL,
  content TEXT NOT NULL,
  author varchar(255) NOT NULL,
  date DATETIME NOT NULL,
  FOREIGN KEY (id_topic) REFERENCES Topic(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;